version: '3.4'
services:
  mongo:
    image: mongo:latest
    container_name: nf_mongo
    restart: always
    environment: 
      - MONGO_INITDB_DATABASE=${DB_NAME:-news_feed}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-mongo}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-mongo}
    volumes:
      - "mongodata:/data/db"
      - "mongoconfig:/data/configdb"
      - "mongodataconfig:/data/dataconfigdb"
    ports:
      - ${MONGO_LOCAL_PORT:-27018}:27017
volumes:
  mongodata: 
  mongoconfig:
  mongodataconfig:
networks:
  default:
    external:
      name: nf
